### PR TITLE
Removed datatype of "KBaseGenomeAnnotations.Assembly"

### PR DESCRIPTION
**Pull request by qzzhang**
Getting rid of the Hybrid_SPAdes unaccepted datatype 'KBaseGenomeAnnotations.Assembly' in the ui spec file.

### CODE REVIEW

**Comment by dcchivian** [comment]
Hi @qzzhang .  I'm confused.  Why did you revert from module version 1.3.2?  Why did you revert from SPAdes v3.15.4?

**Comment by dcchivian** [comment]
Also, It looks like we dropped the memory requirement so Github Actions should execute and I'm confused why they aren't.

**Comment by qzzhang** [comment]
"Why did you revert from module version 1.3.2? Why did you revert from SPAdes v3.15.4?"--The version number v3.15.4 is for the raw SPAdes update, while 1.3.2 is for the KBase wrapper.

**Comment by qzzhang** [comment]
For the memory checking, we have had this checking block of code starting at https://github.com/kbaseapps/kb_SPAdes/blob/master/lib/kb_SPAdes/utils/spades_utils.py#L739

I don't remember that we had dropped the memory check, as shown in the master branch.

**Comment by dcchivian** [comment]
> "Why did you revert from module version 1.3.2? Why did you revert from SPAdes v3.15.4?"--The version number v3.15.4 is for the raw SPAdes update, while 1.3.2 is for the KBase wrapper.

I get that.  But you bumped up both versions and then appear to have brought them back?  You have to at least increase the module version number.

**Comment by dcchivian** [comment]
> For the memory checking, we have had this checking block of code starting at https://github.com/kbaseapps/kb_SPAdes/blob/master/lib/kb_SPAdes/utils/spades_utils.py#L739
> 
> I don't remember that we had dropped the memory check, as shown in the master branch.

Drop MIN_MEMORY_GB to 4 and see if Github Actions unit tests can all run 

https://github.com/kbaseapps/kb_SPAdes/blob/qz_master/lib/kb_SPAdes/utils/spades_utils.py#L85

**Comment by dcchivian** [comment]
small change.  kbase.yaml version updated and RELEASE_NOTES.md updated.  passing unit tests.  PR approved.

**Pull request merged**
